name: flutter_ble_example
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  auto_route: ^9.2.0
  get_it: ^8.0.3
  injectable: ^2.4.4
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  json_serializable: ^6.8.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.1
  flutter_blue_plus: ^1.35.2
  permission_handler: ^11.3.1
  easy_localization: ^3.0.7
  flutter_secure_storage: ^9.2.4
  sizer: ^3.0.5
  logger: ^2.5.0
  sqflite: ^2.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/fonts/
    - lib/assets/translations/
  # fonts:
  #   - family: AdobeClean
  #     fonts:
  #       - asset: assets/fonts/AdobeCleanRegular.otf
  #       - asset: assets/fonts/AdobeCleanBold.otf
  #         weight: 700
  #       - asset: assets/fonts/AdobeCleanLight.otf
  #         weight: 100